name = "lean-eval"
defaultTargets = ["LeanEval"]

[leanOptions]
autoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "6f1ef4e5dd604a435bddba4747b13970cd65d2a1"

[[require]]
name = "Cli"
git = "https://github.com/leanprover/lean4-cli"
rev = "6130a47896ce867c6a4a55373441e59e565bad0f"

[[require]]
name = "lean-eval-generator"
git = "https://github.com/leanprover/lean-eval-generator.git"
rev = "a726789593eeac5c32ad82760061cd5bf6cae662"

[[lean_lib]]
name = "LeanEval"

[[lean_lib]]
name = "EvalTools"

[[lean_exe]]
name = "extract_theorem"
root = "EvalTools.ExtractTheorem"

[[lean_exe]]
name = "eval_inventory"
root = "EvalTools.ProblemInventory"

[[lean_exe]]
name = "lean-eval"
root = "EvalTools.Main"

[[lean_exe]]
name = "test_validate_submission"
srcDir = "tests/lean"
root = "EvalToolsTests.ValidateSubmissionTest"

[[lean_exe]]
name = "test_check_comparator_installation"
srcDir = "tests/lean"
root = "EvalToolsTests.CheckComparatorInstallationTest"

[[lean_exe]]
name = "test_generate"
srcDir = "tests/lean"
root = "EvalToolsTests.GenerateTest"

[[lean_exe]]
name = "test_module_coverage"
srcDir = "tests/lean"
root = "EvalToolsTests.ModuleCoverageTest"
