id = "annals_good_lt_codes"
title = "Good Locally Testable Codes"
test = false
module = "LeanEval.Combinatorics.GoodLTCodes"
holes = ["theorem_1_2"]
submitter = "Thomas Browning, Katerina Hristova"
source = "I. Dinur, S. Evra, R. Livne, A. Lubotzky, and S. Mozes, `Good Locally Testable Codes`, Annals of Math, 203 (2) 2026. Statement taken from https://github.com/ImperialCollegeLondon/AnnalsChallenge (v1.0.0, e32eb14), AnnalsChallenge/AnnalsOfMathematics/2026-203-2-GoodLTCodes.lean"
