id = "annals_lorentzian_polynomials"
title = "Lorentzian polynomials"
test = false
module = "LeanEval.Combinatorics.LorentzianPolynomials"
holes = ["theorem_2_25"]
submitter = "Justus Springer"
source = "P. Brändén and J. Huh, `Lorentzian polynomials`, Annals of Math, 192 (3) 2020. Statement taken from https://github.com/ImperialCollegeLondon/AnnalsChallenge (v1.0.0, e32eb14), AnnalsChallenge/AnnalsOfMathematics/2020-192-3-LorentzianPolynomials.lean"
