id = "annals_ulam"
title = "A negative answer to Ulam's Problem 19 from the Scottish Book"
test = false
module = "LeanEval.ConvexGeometry.Ulam"
holes = ["theorem_1"]
submitter = "Justus Springer"
source = "D. Ryabogin, `A negative answer to Ulam's Problem 19 from the Scottish Book`, Annals of Math, 195 (3) 2022. Statement taken from https://github.com/ImperialCollegeLondon/AnnalsChallenge (v1.0.0, e32eb14), AnnalsChallenge/AnnalsOfMathematics/2022-195-3-Ulam.lean"
