id = "annals_pointwise_ergodic_theorems"
title = "Pointwise ergodic theorems for non-conventional bilinear polynomial averages"
test = false
module = "LeanEval.Dynamics.PointwiseErgodicTheorems"
holes = ["theorem_1_17_i", "theorem_1_17_ii", "Cᵢᵢᵢ", "theorem_1_17_iii", "Cᵢᵥ", "theorem_1_17_iv"]
submitter = "David Ledvinka"
source = "B. Krause, M. Mirek, and T. Tao, `Pointwise ergodic theorems for non-conventional bilinear polynomial averages`, Annals of Math, 195 (3) 2022. Statement taken from https://github.com/ImperialCollegeLondon/AnnalsChallenge (v1.0.0, e32eb14), AnnalsChallenge/AnnalsOfMathematics/2022-195-3-PointwiseErgodicTheorems.lean"
