id = "annals_flat_littlewood_poly"
title = "Flat Littlewood polynomials exist"
test = false
module = "LeanEval.Analysis.FlatLittlewoodPoly"
holes = ["theorem_1_1"]
submitter = "Katerina Hristova, Kevin Buzzard, Bhavik Mehta"
source = "P. Balister, B. Bollobás, R. Morris, J. Sahasrabudhe, and M. Tiba, `Flat Littlewood polynomials exist`, Annals of Math, 192 (3) 2020. Statement taken from https://github.com/ImperialCollegeLondon/AnnalsChallenge (v1.0.0, e32eb14), AnnalsChallenge/AnnalsOfMathematics/2020-192-3-FlatLittlewoodPoly.lean"
