id = "annals_wilkies_conjecture"
title = "Wilkie's conjecture for Pfaffian structures"
test = false
module = "LeanEval.ModelTheory.WilkiesConjecture"
holes = ["corollary_1"]
submitter = "Justus Springer, Mathias Stout"
source = "G. Binyamini, D. Novikov, and B. Zak, `Wilkie's conjecture for Pfaffian structures`, Annals of Math, 199 (2) 2024. Statement taken from https://github.com/ImperialCollegeLondon/AnnalsChallenge (v1.0.0, e32eb14), AnnalsChallenge/AnnalsOfMathematics/2024-199-2-WilkiesConjecture.lean"
