id = "annals_van_der_waerden_conjecture"
title = "Galois groups of random integer polynomials and van der Waerden's Conjecture"
test = false
module = "LeanEval.NumberTheory.VanDerWaerdenConjecture"
holes = ["theorem_1"]
submitter = "David Ledvinka"
source = "M. Bhargava, `Galois groups of random integer polynomials and van der Waerden's Conjecture`, Annals of Math, 201 (2) 2025. Statement taken from https://github.com/ImperialCollegeLondon/AnnalsChallenge (v1.0.0, e32eb14), AnnalsChallenge/AnnalsOfMathematics/2025-201-2-vanDerWaerdenConjecture.lean"
