id = "annals_enumerating_number_fields"
title = "Enumerating number fields"
test = false
module = "LeanEval.NumberTheory.EnumeratingNumberFields"
holes = ["theorem_1", "theorem_2"]
submitter = "Thomas Browning"
source = "J.-M. Couveignes, `Enumerating number fields`, Annals of Math, 192 (2) 2020. Statement taken from https://github.com/ImperialCollegeLondon/AnnalsChallenge (v1.0.0, e32eb14), AnnalsChallenge/AnnalsOfMathematics/2020-192-2-EnumeratingNumberFields.lean"
