id = "annals_mckay_conjecture"
title = "The McKay Conjecture on character degrees"
test = false
module = "LeanEval.RepresentationTheory.McKayConjecture"
holes = ["theorem_1_1"]
submitter = "Thomas Browning"
source = "M. Cabanes and B. Späth, `The McKay Conjecture on character degrees`, Annals of Math, 203 (3) 2026. Statement taken from https://github.com/ImperialCollegeLondon/AnnalsChallenge (v1.0.0, e32eb14), AnnalsChallenge/AnnalsOfMathematics/2026-203-3-McKayConjecture.lean"
