id = "annals_erdos_supersingular_primes"
title = "A conjecture of Erdős, supersingular primes and short character sums"
test = false
module = "LeanEval.NumberTheory.ErdosSupersingularPrimes"
holes = ["k₀", "theorem_2"]
submitter = "Justus Springer"
source = "M. Bennett and S. Siksek, `A conjecture of Erdős, supersingular primes and short character sums`, Annals of Math, 191 (2) 2020. Statement taken from https://github.com/ImperialCollegeLondon/AnnalsChallenge (v1.0.0, e32eb14), AnnalsChallenge/AnnalsOfMathematics/2020-191-2-ErdosSupersingularPrimes.lean"
