id = "cdt_linearIndependent"
title = "Linear independence results of Calegari–Dimitrov–Tang"
test = false
module = "LeanEval.NumberTheory.CalegariDimitrovTangLinearIndependent"
holes = ["cdt_linearIndependent"]
submitter = "Junyan Xu"
source = "https://arxiv.org/abs/2408.15403"
informal_solution = "See Figure 1.3.0. 'Leitfaden: paths to Theorems A and C' for a dependency graph of the results. The dotted lines indicates that there are two alternate paths to Theorems A and C, either through § 6 (by multivariable methods, based on measure concentration) or § 7 (by single variable methods, based on some Arakelov theory and Bost’s inequality on evaluation heights). Arithmetic holonomy bounds are ultimately the main concern of this paper."
