id = "complHandlebodyHomeomorph"
title = "The complement of a 3-dimensional handlebody"
test = false
module = "LeanEval.Topology.Prelude"
holes = ["complHandlebody₃Homeomorph"]
submitter = "Junyan Xu"
