id = "mostow_rigidity"
title = "Mostow rigidity"
test = false
module = "LeanEval.Geometry.MostowRigidity"
holes = ["mostow_rigidity"]
submitter = "Junyan Xu"
source = "https://en.wikipedia.org/wiki/Mostow_rigidity_theorem#Algebraic_form"